/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LaunchCampaign {
  export type InitParamsStruct = {
    name: string;
    symbol: string;
    metadataURI: string;
    totalSupply: BigNumberish;
    curveBps: BigNumberish;
    liquidityTokenBps: BigNumberish;
    basePrice: BigNumberish;
    priceSlope: BigNumberish;
    graduationTarget: BigNumberish;
    liquidityBps: BigNumberish;
    protocolFeeBps: BigNumberish;
    router: AddressLike;
    lpReceiver: AddressLike;
    feeRecipient: AddressLike;
    creator: AddressLike;
    factory: AddressLike;
  };

  export type InitParamsStructOutput = [
    name: string,
    symbol: string,
    metadataURI: string,
    totalSupply: bigint,
    curveBps: bigint,
    liquidityTokenBps: bigint,
    basePrice: bigint,
    priceSlope: bigint,
    graduationTarget: bigint,
    liquidityBps: bigint,
    protocolFeeBps: bigint,
    router: string,
    lpReceiver: string,
    feeRecipient: string,
    creator: string,
    factory: string
  ] & {
    name: string;
    symbol: string;
    metadataURI: string;
    totalSupply: bigint;
    curveBps: bigint;
    liquidityTokenBps: bigint;
    basePrice: bigint;
    priceSlope: bigint;
    graduationTarget: bigint;
    liquidityBps: bigint;
    protocolFeeBps: bigint;
    router: string;
    lpReceiver: string;
    feeRecipient: string;
    creator: string;
    factory: string;
  };
}

export interface LaunchCampaignInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "basePrice"
      | "buyExactTokens"
      | "creatorReserve"
      | "currentPrice"
      | "curveSupply"
      | "factory"
      | "feeRecipient"
      | "finalize"
      | "finalizedAt"
      | "graduationTarget"
      | "launched"
      | "liquidityBps"
      | "liquiditySupply"
      | "lpReceiver"
      | "metadataURI"
      | "owner"
      | "priceSlope"
      | "protocolFeeBps"
      | "quoteBuyExactTokens"
      | "quoteSellExactTokens"
      | "renounceOwnership"
      | "router"
      | "sellExactTokens"
      | "sold"
      | "token"
      | "totalSupply"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignFinalized"
      | "OwnershipTransferred"
      | "TokensPurchased"
      | "TokensSold"
  ): EventFragment;

  encodeFunctionData(functionFragment: "basePrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyExactTokens",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "curveSupply",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalize",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizedAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "graduationTarget",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "launched", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "liquidityBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquiditySupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lpReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "metadataURI",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceSlope",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteBuyExactTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteSellExactTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sellExactTokens",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sold", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "basePrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "curveSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finalize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "graduationTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "launched", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidityBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquiditySupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpReceiver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "metadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceSlope", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteBuyExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteSellExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sold", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CampaignFinalizedEvent {
  export type InputTuple = [
    caller: AddressLike,
    liquidityTokens: BigNumberish,
    liquidityBnb: BigNumberish,
    protocolFee: BigNumberish,
    creatorPayout: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    liquidityTokens: bigint,
    liquidityBnb: bigint,
    protocolFee: bigint,
    creatorPayout: bigint
  ];
  export interface OutputObject {
    caller: string;
    liquidityTokens: bigint;
    liquidityBnb: bigint;
    protocolFee: bigint;
    creatorPayout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    amountOut: BigNumberish,
    cost: BigNumberish
  ];
  export type OutputTuple = [buyer: string, amountOut: bigint, cost: bigint];
  export interface OutputObject {
    buyer: string;
    amountOut: bigint;
    cost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensSoldEvent {
  export type InputTuple = [
    seller: AddressLike,
    amountIn: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [seller: string, amountIn: bigint, payout: bigint];
  export interface OutputObject {
    seller: string;
    amountIn: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LaunchCampaign extends BaseContract {
  connect(runner?: ContractRunner | null): LaunchCampaign;
  waitForDeployment(): Promise<this>;

  interface: LaunchCampaignInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  basePrice: TypedContractMethod<[], [bigint], "view">;

  buyExactTokens: TypedContractMethod<
    [amountOut: BigNumberish, maxCost: BigNumberish],
    [bigint],
    "payable"
  >;

  creatorReserve: TypedContractMethod<[], [bigint], "view">;

  currentPrice: TypedContractMethod<[], [bigint], "view">;

  curveSupply: TypedContractMethod<[], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  finalize: TypedContractMethod<
    [minTokens: BigNumberish, minBnb: BigNumberish],
    [[bigint, bigint] & { usedTokens: bigint; usedBnb: bigint }],
    "nonpayable"
  >;

  finalizedAt: TypedContractMethod<[], [bigint], "view">;

  graduationTarget: TypedContractMethod<[], [bigint], "view">;

  launched: TypedContractMethod<[], [boolean], "view">;

  liquidityBps: TypedContractMethod<[], [bigint], "view">;

  liquiditySupply: TypedContractMethod<[], [bigint], "view">;

  lpReceiver: TypedContractMethod<[], [string], "view">;

  metadataURI: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  priceSlope: TypedContractMethod<[], [bigint], "view">;

  protocolFeeBps: TypedContractMethod<[], [bigint], "view">;

  quoteBuyExactTokens: TypedContractMethod<
    [amountOut: BigNumberish],
    [bigint],
    "view"
  >;

  quoteSellExactTokens: TypedContractMethod<
    [amountIn: BigNumberish],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  router: TypedContractMethod<[], [string], "view">;

  sellExactTokens: TypedContractMethod<
    [amountIn: BigNumberish, minPayout: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  sold: TypedContractMethod<[], [bigint], "view">;

  token: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "basePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyExactTokens"
  ): TypedContractMethod<
    [amountOut: BigNumberish, maxCost: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "creatorReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "curveSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalize"
  ): TypedContractMethod<
    [minTokens: BigNumberish, minBnb: BigNumberish],
    [[bigint, bigint] & { usedTokens: bigint; usedBnb: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizedAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "graduationTarget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "launched"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "liquidityBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquiditySupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "metadataURI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceSlope"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quoteBuyExactTokens"
  ): TypedContractMethod<[amountOut: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "quoteSellExactTokens"
  ): TypedContractMethod<[amountIn: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sellExactTokens"
  ): TypedContractMethod<
    [amountIn: BigNumberish, minPayout: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CampaignFinalized"
  ): TypedContractEvent<
    CampaignFinalizedEvent.InputTuple,
    CampaignFinalizedEvent.OutputTuple,
    CampaignFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "TokensSold"
  ): TypedContractEvent<
    TokensSoldEvent.InputTuple,
    TokensSoldEvent.OutputTuple,
    TokensSoldEvent.OutputObject
  >;

  filters: {
    "CampaignFinalized(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      CampaignFinalizedEvent.InputTuple,
      CampaignFinalizedEvent.OutputTuple,
      CampaignFinalizedEvent.OutputObject
    >;
    CampaignFinalized: TypedContractEvent<
      CampaignFinalizedEvent.InputTuple,
      CampaignFinalizedEvent.OutputTuple,
      CampaignFinalizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokensPurchased(address,uint256,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "TokensSold(address,uint256,uint256)": TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
    TokensSold: TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
  };
}
