/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TreasuryRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptVault"
      | "activeVault"
      | "admin"
      | "forward"
      | "forwardingPaused"
      | "pendingSince"
      | "pendingVault"
      | "proposeVault"
      | "setForwardingPaused"
      | "upgradeDelay"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ForwardFailed"
      | "Forwarded"
      | "ForwardingPaused"
      | "VaultActivated"
      | "VaultProposed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "forward", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "forwardingPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingSince",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setForwardingPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeDelay",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "forward", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forwardingPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingSince",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setForwardingPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeDelay",
    data: BytesLike
  ): Result;
}

export namespace ForwardFailedEvent {
  export type InputTuple = [vault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForwardedEvent {
  export type InputTuple = [vault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForwardingPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultActivatedEvent {
  export type InputTuple = [oldVault: AddressLike, newVault: AddressLike];
  export type OutputTuple = [oldVault: string, newVault: string];
  export interface OutputObject {
    oldVault: string;
    newVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultProposedEvent {
  export type InputTuple = [newVault: AddressLike, executeAfter: BigNumberish];
  export type OutputTuple = [newVault: string, executeAfter: bigint];
  export interface OutputObject {
    newVault: string;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryRouter extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryRouter;
  waitForDeployment(): Promise<this>;

  interface: TreasuryRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptVault: TypedContractMethod<[], [void], "nonpayable">;

  activeVault: TypedContractMethod<[], [string], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  forward: TypedContractMethod<[], [void], "nonpayable">;

  forwardingPaused: TypedContractMethod<[], [boolean], "view">;

  pendingSince: TypedContractMethod<[], [bigint], "view">;

  pendingVault: TypedContractMethod<[], [string], "view">;

  proposeVault: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  setForwardingPaused: TypedContractMethod<
    [paused: boolean],
    [void],
    "nonpayable"
  >;

  upgradeDelay: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptVault"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activeVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "forward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forwardingPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingSince"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setForwardingPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeDelay"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ForwardFailed"
  ): TypedContractEvent<
    ForwardFailedEvent.InputTuple,
    ForwardFailedEvent.OutputTuple,
    ForwardFailedEvent.OutputObject
  >;
  getEvent(
    key: "Forwarded"
  ): TypedContractEvent<
    ForwardedEvent.InputTuple,
    ForwardedEvent.OutputTuple,
    ForwardedEvent.OutputObject
  >;
  getEvent(
    key: "ForwardingPaused"
  ): TypedContractEvent<
    ForwardingPausedEvent.InputTuple,
    ForwardingPausedEvent.OutputTuple,
    ForwardingPausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultActivated"
  ): TypedContractEvent<
    VaultActivatedEvent.InputTuple,
    VaultActivatedEvent.OutputTuple,
    VaultActivatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultProposed"
  ): TypedContractEvent<
    VaultProposedEvent.InputTuple,
    VaultProposedEvent.OutputTuple,
    VaultProposedEvent.OutputObject
  >;

  filters: {
    "ForwardFailed(address,uint256)": TypedContractEvent<
      ForwardFailedEvent.InputTuple,
      ForwardFailedEvent.OutputTuple,
      ForwardFailedEvent.OutputObject
    >;
    ForwardFailed: TypedContractEvent<
      ForwardFailedEvent.InputTuple,
      ForwardFailedEvent.OutputTuple,
      ForwardFailedEvent.OutputObject
    >;

    "Forwarded(address,uint256)": TypedContractEvent<
      ForwardedEvent.InputTuple,
      ForwardedEvent.OutputTuple,
      ForwardedEvent.OutputObject
    >;
    Forwarded: TypedContractEvent<
      ForwardedEvent.InputTuple,
      ForwardedEvent.OutputTuple,
      ForwardedEvent.OutputObject
    >;

    "ForwardingPaused(bool)": TypedContractEvent<
      ForwardingPausedEvent.InputTuple,
      ForwardingPausedEvent.OutputTuple,
      ForwardingPausedEvent.OutputObject
    >;
    ForwardingPaused: TypedContractEvent<
      ForwardingPausedEvent.InputTuple,
      ForwardingPausedEvent.OutputTuple,
      ForwardingPausedEvent.OutputObject
    >;

    "VaultActivated(address,address)": TypedContractEvent<
      VaultActivatedEvent.InputTuple,
      VaultActivatedEvent.OutputTuple,
      VaultActivatedEvent.OutputObject
    >;
    VaultActivated: TypedContractEvent<
      VaultActivatedEvent.InputTuple,
      VaultActivatedEvent.OutputTuple,
      VaultActivatedEvent.OutputObject
    >;

    "VaultProposed(address,uint64)": TypedContractEvent<
      VaultProposedEvent.InputTuple,
      VaultProposedEvent.OutputTuple,
      VaultProposedEvent.OutputObject
    >;
    VaultProposed: TypedContractEvent<
      VaultProposedEvent.InputTuple,
      VaultProposedEvent.OutputTuple,
      VaultProposedEvent.OutputObject
    >;
  };
}
