/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITreasuryVault,
  ITreasuryVaultInterface,
} from "../../contracts/ITreasuryVault";

const _abi = [
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class ITreasuryVault__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasuryVaultInterface {
    return new Interface(_abi) as ITreasuryVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITreasuryVault {
    return new Contract(address, _abi, runner) as unknown as ITreasuryVault;
  }
}
