/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  TreasuryVault,
  TreasuryVaultInterface,
} from "../../contracts/TreasuryVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_multisig",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [],
    name: "multisig",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60a0346100a857601f61032138819003918201601f19168301916001600160401b038311848410176100ad578084926020946040528339810103126100a857516001600160a01b0381168082036100a857156100765760805260405161025d90816100c48239608051818181606f015261021d0152f35b60405162461bcd60e51b815260206004820152600a60248201526906d756c74697369673d360b41b6044820152606490fd5b600080fd5b634e487b7160e01b600052604160045260246000fdfe60806040818152600480361015610021575b505050361561001f57600080fd5b005b600092833560e01c9081634783c35b14610209575063f3fef3a30361001157346102055781600319360112610205576001600160a01b038135818116939192908490036102015760248035937f00000000000000000000000000000000000000000000000000000000000000001633036101d15784156101aa5747841161017a578580808087895af13d15610175576001600160401b033d81811161016357855191601f8201601f19908116603f011683019081118382101761015157865281528760203d92013e5b1561011e5750507f884edad9ce6fa2440d8a54cc123490eb96d2768479d49ff9c7366125a94243649160209151908152a280f35b600f906020606494519362461bcd60e51b85528401528201526e1d1c985b9cd9995c8819985a5b1959608a1b6044820152fd5b634e487b7160e01b8a5260418652848afd5b634e487b7160e01b8952604185528389fd5b6100ea565b600c906020606494519362461bcd60e51b85528401528201526b1a5b9cdd59999a58da595b9d60a21b6044820152fd5b915162461bcd60e51b815260208183015291820152630746f3d360e41b6044820152606490fd5b600c906020606494519362461bcd60e51b85528401528201526b6e6f74206d756c746973696760a01b6044820152fd5b8480fd5b8280fd5b84903461024c578160031936011261024c577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b5080fdfea164736f6c6343000818000a";

type TreasuryVaultConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TreasuryVaultConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TreasuryVault__factory extends ContractFactory {
  constructor(...args: TreasuryVaultConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _multisig: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_multisig, overrides || {});
  }
  override deploy(
    _multisig: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_multisig, overrides || {}) as Promise<
      TreasuryVault & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TreasuryVault__factory {
    return super.connect(runner) as TreasuryVault__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TreasuryVaultInterface {
    return new Interface(_abi) as TreasuryVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TreasuryVault {
    return new Contract(address, _abi, runner) as unknown as TreasuryVault;
  }
}
