// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IPancakeRouter02$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IPancakeRouter02";
  readonly sourceName: "contracts/interfaces/IPancakeRouter02.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"amountTokenDesired","type":"uint256"},{"internalType":"uint256","name":"amountTokenMin","type":"uint256"},{"internalType":"uint256","name":"amountETHMin","type":"uint256"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"deadline","type":"uint256"}],"name":"addLiquidityETH","outputs":[{"internalType":"uint256","name":"amountToken","type":"uint256"},{"internalType":"uint256","name":"amountETH","type":"uint256"},{"internalType":"uint256","name":"liquidity","type":"uint256"}],"stateMutability":"payable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPancakeRouter02.sol";
  readonly buildInfoId: "solc-0_8_23-685ea5b4f0282f1980be4066b166a92a506ab2dd";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IPancakeRouter02"]: IPancakeRouter02$Type;
    ["contracts/interfaces/IPancakeRouter02.sol:IPancakeRouter02"]: IPancakeRouter02$Type;
  }
}