/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  RevertingReceiver,
  RevertingReceiverInterface,
} from "../../../contracts/mocks/RevertingReceiver";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608080604052346014576079908161001a8239f35b600080fdfe6080806040523615603d5760405162461bcd60e51b815260206004820152600b60248201526a4e4f5f46414c4c4241434b60a81b6044820152606490fd5b62461bcd60e51b815260206004820152600a6024820152694e4f5f5245434549564560b01b6044820152606490fdfea164736f6c6343000818000a";

type RevertingReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RevertingReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RevertingReceiver__factory extends ContractFactory {
  constructor(...args: RevertingReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RevertingReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RevertingReceiver__factory {
    return super.connect(runner) as RevertingReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RevertingReceiverInterface {
    return new Interface(_abi) as RevertingReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RevertingReceiver {
    return new Contract(address, _abi, runner) as unknown as RevertingReceiver;
  }
}
